version: '3.9'
services:
  secure-chat:
    image: secure-chat-container:latest
    restart: always
    environment:
      DB_POSTGRES_HOST: host.docker.internal
      APPLICATION_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
