version: '3.9'
services:
  db:
    image: postgres:13.7 # same as on prod
    restart: always
    environment:
      postgres: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5678:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
