version: '3.9'
services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      postgres: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5678:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
