version: '3.9'
services:
  secure-chat:
    image: secure-chat-container:latest
    restart: always
    environment:
      DB_POSTGRES_HOST: host.docker.internal
    ports:
      - "8083:8080"
    depends_on:
      - db
