name: get-source-branch-2
on: workflow_dispatch
env:
  REF: ${{ github.ref }}
  REF_NAME: ${{ github.ref_name }}
  HEAD_REF: ${{ github.head_ref }}
jobs: 
  pring_branch_name:
    runs-on: ubuntu-latest
    steps:
      - run: echo $REF
      - run: echo $REF_NAME
      - run: echo $HEAD_REF
